services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distribox-backend
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_NAME:-distribox}
      - POSTGRES_USER=${POSTGRES_USER:-distribox_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-distribox_password}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - ./backend:/backend
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/distribox:/var/lib/distribox
    depends_on:
      database:
        condition: service_healthy
    networks:
      - distribox-network

volumes:
  backend:

networks:
  distribox-network:
    name: distribox-network
