services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    container_name: distribox-backend
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_NAME=${POSTGRES_NAME:-distribox}
      - POSTGRES_USER=${POSTGRES_USER:-distribox_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-distribox_password}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DISTRIBOX_SECRET=${DISTRIBOX_SECRET:-secret}
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/distribox:/var/lib/distribox
    depends_on:
      database:
        condition: service_healthy
    networks:
      - distribox-network
    profiles: ["prod"]


  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-stage
    container_name: distribox-backend-dev
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_NAME=${POSTGRES_NAME:-distribox}
      - POSTGRES_USER=${POSTGRES_USER:-distribox_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-distribox_password}
      - BACKEND_PORT=${BACKEND_PORT:-8080}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DISTRIBOX_BUCKET_REGISTRY=${DISTRIBOX_BUCKET_REGISTRY:-distribox-images}
      - AWS_REGION=${AWS_REGION:-eu-west-3}
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}"
    volumes:
      - ./app:/code/app
      - ./.env:/code/.env
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/distribox:/var/lib/distribox
    depends_on:
      database:
        condition: service_healthy
    networks:
      - distribox-network
    profiles: ["dev"]

volumes:
  backend:

networks:
  distribox-network:
    name: distribox-network
